version: "2"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
    ports:
      - "1883:1883"
    networks:
      - kafka_mqtt_network

  kafka-connect:
    image: confluentinc/cp-kafka-connect:5.1.0
    hostname: kafka-connect
    container_name: kafka-connect
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka.example.com:9092
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/plugins
      CONNECT_LOG4J_ROOT_LOGLEVEL: WARN
      # CONNECT_SECURITY_PROTOCOL: SSL
      # CONNECT_SSL_TRUSTSTORE_LOCATION: /var/private/ssl/truststore.jks
      # CONNECT_SSL_TRUSTSTORE_PASSWORD: change-this-password
      # CONNECT_SSL_KEYSTORE_LOCATION: /var/private/ssl/keystore.jks
      # CONNECT_SSL_KEYSTORE_PASSWORD: change-this-password
      # CONNECT_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      # CONNECT_PRODUCER_SECURITY_PROTOCOL: SSL
      # CONNECT_PRODUCER_SSL_TRUSTSTORE_LOCATION: /var/private/ssl/truststore.jks
      # CONNECT_PRODUCER_SSL_TRUSTSTORE_PASSWORD: change-this-password
      # CONNECT_PRODUCER_SSL_KEYSTORE_LOCATION: /var/private/ssl/keystore.jks
      # CONNECT_PRODUCER_SSL_KEYSTORE_PASSWORD: change-this-password
      # CONNECT_PRODUCER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
    volumes:
      - ./plugins:/etc/kafka-connect/plugins
      # - /local/path/to/truststore.jks:/var/private/ssl/truststore.jks
      # - /local/path/to/keystore.jks:/var/private/ssl/keystore.jks
    depends_on:
      - mosquitto
    networks:
      - kafka_mqtt_network

networks:
  kafka_mqtt_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.8.8.0/24
