name: build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 9, 11, 14 ]

    steps:
    - name: Checkout GitHub sources
      uses: actions/checkout@v2
    - name: Setup JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        server-id: maven.tenefit.com
        java-version: ${{ matrix.java }}
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: ./mvnw -B -nsu verify
      env:
        GITHUB_ACTOR: ${{ secrets.TENEFIT_GITHUB_ACTOR }}
        GITHUB_TOKEN: ${{ secrets.TENEFIT_GITHUB_TOKEN }}
